import jwt

# New token
token = "eyJhbGciOiJIUzI1NiIsImtpZCI6IjFwcjFDVWlETEFaYXJhYlkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2tzcnZ0dnFxaWt3amJxenBnYWNzLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlZWMwODkwNS0wZTIyLTQyYWItOGM0Ni1lMjBlZDViODgwNDUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU3NzEyOTAxLCJpYXQiOjE3NTc3MDkzMDEsImVtYWlsIjoidGVzdC11c2VyLTEyM0B0ZXN0LWRvbWFpbi5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoidGVzdC11c2VyLTEyM0B0ZXN0LWRvbWFpbi5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZWVjMDg5MDUtMGUyMi00MmFiLThjNDYtZTIwZWQ1Yjg4MDQ1In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTc3MDkzMDF9XSwic2Vzc2lvbl9pZCI6ImYzNzUxZTBhLWVmZmItNGYzOC1iMmVjLWViMmQ2MGYxMDgwMiIsImlzX2Fub255bW91cyI6ZmFsc2V9.TRoEAuEjdtYHsFX66ZbJIKwWYsUqcwPmuBetg8lu6yI"

# Decode without verification to see the audience
payload = jwt.decode(token, options={"verify_signature": False})
print("Token payload:")
print(payload)
print(f"Audience in token: {payload.get('aud')}")
print(f"Type of audience: {type(payload.get('aud'))}")