"""
Test script to verify Supabase data operations
"""

import os
import sys
from datetime import datetime
# Load environment variables from .env file
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Add the parent directory to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from maya_supabase.models import Council, Proposal, TreasuryTransaction, CouncilOpportunity
from maya_supabase.database import SupabaseService

def main():
    # Initialize the database service (will use environment variables from .env)
    print("Initializing Supabase service...")
    db_service = SupabaseService()
    
    if db_service.client is None:
        print("Warning: Supabase client not initialized. Check your .env file for SUPABASE_URL and SUPABASE_KEY")
        print("Current environment variables:")
        print(f"  SUPABASE_URL: {os.getenv('SUPABASE_URL', 'Not set')}")
        print(f"  SUPABASE_KEY: {'*' * len(os.getenv('SUPABASE_KEY', '')) if os.getenv('SUPABASE_KEY') else 'Not set'}")
        return
    
    print("Supabase client initialized successfully!")
    
    # Test data creation
    print("\nCreating test data...")
    
    # Create a council
    council = Council(
        id="council_digital_identity",
        council_name="Council of Digital Identity",
        domain_description="Responsible for managing digital identities and authentication systems across the Digital Kingdom",
        revenue_model_description="Earns revenue through licensing fees for identity verification services and partnerships with other protocols",
        ethical_boundary="Must ensure user privacy and data protection while maintaining system integrity",
        status="ACTIVE",
        created_at=datetime.now()
    )
    print(f"Created council: {council.council_name}")
    
    # Create a proposal
    proposal = Proposal(
        id=None,  # This will be auto-generated by Supabase
        council_id="council_digital_identity",
        purpose="Launch 'Sign-In with Bitcoin' service",
        cost_eth=10.5,
        expected_monthly_revenue_btc=0.25,
        status="PENDING_REVIEW",
        details_json={
            "technical_requirements": ["Bitcoin node integration", "wallet connector"],
            "timeline": "3 months"
        },
        submitted_at=datetime.now(),
        last_status_update_at=datetime.now(),
        roi_score=8.5
    )
    print(f"Created proposal: {proposal.purpose}")
    
    # Create a treasury transaction
    transaction = TreasuryTransaction(
        id=None,  # This will be auto-generated by Supabase
        timestamp=datetime.now(),
        transaction_type="COUNCIL_REVENUE_IN",
        council_id="council_digital_identity",
        asset="ETH",
        amount=5.25,
        related_onchain_transaction_hash="0x123456789abcdef",
        description="Revenue from identity verification services",
        status="COMPLETED"
    )
    print(f"Created transaction: {transaction.transaction_type}")
    
    # Create a council opportunity
    opportunity = CouncilOpportunity(
        id=None,  # This will be auto-generated by Supabase
        council_id="council_digital_identity",
        opportunity_description="Partnership opportunity with major DeFi protocol for identity verification services",
        reported_at=datetime.now(),
        potential_cost_eth=2.0,
        potential_revenue_btc=0.1,
        status="NEW"
    )
    print(f"Created opportunity: {opportunity.opportunity_description}")
    
    # Perform database operations
    print("\nPerforming database operations...")
    
    # Create records in the database
    created_council = db_service.create_council(council)
    if created_council:
        print(f"✓ Saved council to database: {created_council.council_name}")
    else:
        print("✗ Failed to save council to database")
        return
    
    created_proposal = db_service.create_proposal(proposal)
    if created_proposal:
        print(f"✓ Saved proposal to database: {created_proposal.purpose}")
    else:
        print("✗ Failed to save proposal to database")
        return
    
    created_transaction = db_service.create_treasury_transaction(transaction)
    if created_transaction:
        print(f"✓ Saved transaction to database: {created_transaction.transaction_type}")
    else:
        print("✗ Failed to save transaction to database")
        return
    
    created_opportunity = db_service.create_council_opportunity(opportunity)
    if created_opportunity:
        print(f"✓ Saved opportunity to database: {created_opportunity.opportunity_description}")
    else:
        print("✗ Failed to save opportunity to database")
        return
    
    # Retrieve records from the database
    print("\nRetrieving records from database...")
    
    retrieved_council = db_service.get_council("council_digital_identity")
    if retrieved_council:
        print(f"✓ Retrieved council from database: {retrieved_council.council_name}")
    else:
        print("✗ Failed to retrieve council from database")
    
    # Get all councils
    all_councils = db_service.get_all_councils()
    print(f"✓ Retrieved {len(all_councils)} councils from database")
    
    # Get all proposals
    all_proposals = db_service.get_all_proposals()
    print(f"✓ Retrieved {len(all_proposals)} proposals from database")
    
    # Get all transactions
    all_transactions = db_service.get_all_treasury_transactions()
    print(f"✓ Retrieved {len(all_transactions)} transactions from database")
    
    # Get all opportunities
    all_opportunities = db_service.get_all_council_opportunities()
    print(f"✓ Retrieved {len(all_opportunities)} opportunities from database")
    
    print("\n🎉 All tests completed successfully!")
    print("The Supabase integration is working correctly with all tables.")

if __name__ == "__main__":
    main()