"""
Example usage of the Supabase integration
"""

import os
import sys
from datetime import datetime

# Add the parent directory to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from maya_supabase.models import Council, Proposal, TreasuryTransaction, CouncilOpportunity
from maya_supabase.database import SupabaseService

def main():
    # Set your Supabase credentials (replace with your actual credentials)
    # os.environ["SUPABASE_URL"] = "https://your-project.supabase.co"
    # os.environ["SUPABASE_KEY"] = "your-supabase-key"
    
    # Initialize the database service
    print("Initializing Supabase service...")
    db_service = SupabaseService()
    
    if db_service.client is None:
        print("Warning: Supabase client not available. Please set SUPABASE_URL and SUPABASE_KEY environment variables.")
        print("Continuing with example data creation (no database operations will be performed)...")
    
    # Create example data
    print("\nCreating example data...")
    
    # Create a council
    council = Council(
        id="council_digital_identity",
        council_name="Council of Digital Identity",
        domain_description="Responsible for managing digital identities and authentication systems across the Digital Kingdom",
        revenue_model_description="Earns revenue through licensing fees for identity verification services and partnerships with other protocols",
        ethical_boundary="Must ensure user privacy and data protection while maintaining system integrity",
        status="ACTIVE",
        created_at=datetime.now()
    )
    print(f"Created council: {council.council_name}")
    
    # Create a proposal
    proposal = Proposal(
        id=None,  # This will be auto-generated by Supabase
        council_id="council_digital_identity",
        purpose="Launch 'Sign-In with Bitcoin' service",
        cost_eth=10.5,
        expected_monthly_revenue_btc=0.25,
        status="PENDING_REVIEW",
        details_json={
            "technical_requirements": ["Bitcoin node integration", "wallet connector"],
            "timeline": "3 months"
        },
        submitted_at=datetime.now(),
        last_status_update_at=datetime.now(),
        roi_score=8.5
    )
    print(f"Created proposal: {proposal.purpose}")
    
    # Create a treasury transaction
    transaction = TreasuryTransaction(
        id=None,  # This will be auto-generated by Supabase
        timestamp=datetime.now(),
        transaction_type="COUNCIL_REVENUE_IN",
        council_id="council_digital_identity",
        asset="ETH",
        amount=5.25,
        related_onchain_transaction_hash="0x123456789abcdef",
        description="Revenue from identity verification services",
        status="COMPLETED"
    )
    print(f"Created transaction: {transaction.transaction_type}")
    
    # Create a council opportunity
    opportunity = CouncilOpportunity(
        id=None,  # This will be auto-generated by Supabase
        council_id="council_digital_identity",
        opportunity_description="Partnership opportunity with major DeFi protocol for identity verification services",
        reported_at=datetime.now(),
        potential_cost_eth=2.0,
        potential_revenue_btc=0.1,
        status="NEW"
    )
    print(f"Created opportunity: {opportunity.opportunity_description}")
    
    # If Supabase is configured, demonstrate database operations
    if db_service.client is not None:
        print("\nPerforming database operations...")
        
        # Create records in the database
        created_council = db_service.create_council(council)
        if created_council:
            print(f"Saved council to database: {created_council.council_name}")
        
        created_proposal = db_service.create_proposal(proposal)
        if created_proposal:
            print(f"Saved proposal to database: {created_proposal.purpose}")
        
        created_transaction = db_service.create_treasury_transaction(transaction)
        if created_transaction:
            print(f"Saved transaction to database: {created_transaction.transaction_type}")
        
        created_opportunity = db_service.create_council_opportunity(opportunity)
        if created_opportunity:
            print(f"Saved opportunity to database: {created_opportunity.opportunity_description}")
        
        # Retrieve records from the database
        retrieved_council = db_service.get_council("council_digital_identity")
        if retrieved_council:
            print(f"Retrieved council from database: {retrieved_council.council_name}")
        
        # Note: For records with auto-generated IDs, you would need to get the ID from the created object
        # retrieved_proposal = db_service.get_proposal(created_proposal.id)
        # if retrieved_proposal:
        #     print(f"Retrieved proposal from database: {retrieved_proposal.purpose}")
    else:
        print("\nSupabase is not configured. Skipping database operations.")
        print("To enable database operations, set the SUPABASE_URL and SUPABASE_KEY environment variables.")
    
    print("\nExample completed successfully!")

if __name__ == "__main__":
    main()