"""
Sample data and usage examples for the Supabase integration
"""

from datetime import datetime
from models import Council, Proposal, TreasuryTransaction, CouncilOpportunity

# Sample Council data
sample_council = Council(
    id="council_digital_identity",
    council_name="Council of Digital Identity",
    domain_description="Responsible for managing digital identities and authentication systems across the Digital Kingdom",
    revenue_model_description="Earns revenue through licensing fees for identity verification services and partnerships with other protocols",
    ethical_boundary="Must ensure user privacy and data protection while maintaining system integrity",
    status="ACTIVE",
    created_at=datetime.now()
)

# Sample Proposal data
sample_proposal = Proposal(
    id=None,  # This will be auto-generated by Supabase
    council_id="council_digital_identity",
    purpose="Launch 'Sign-In with Bitcoin' service",
    cost_eth=10.5,
    expected_monthly_revenue_btc=0.25,
    status="PENDING_REVIEW",
    details_json={
        "technical_requirements": ["Bitcoin node integration", "wallet connector"],
        "timeline": "3 months"
    },
    submitted_at=datetime.now(),
    last_status_update_at=datetime.now(),
    sovereign_approved_at=None,
    funding_transaction_hash=None,
    roi_score=8.5
)

# Sample Treasury Transaction data
sample_transaction = TreasuryTransaction(
    id=None,  # This will be auto-generated by Supabase
    timestamp=datetime.now(),
    transaction_type="COUNCIL_REVENUE_IN",
    council_id="council_digital_identity",
    proposal_id=None,
    asset="ETH",
    amount=5.25,
    related_onchain_transaction_hash="0x123456789abcdef",
    description="Revenue from identity verification services",
    status="COMPLETED"
)

# Sample Council Opportunity data
sample_opportunity = CouncilOpportunity(
    id=None,  # This will be auto-generated by Supabase
    council_id="council_digital_identity",
    opportunity_description="Partnership opportunity with major DeFi protocol for identity verification services",
    reported_at=datetime.now(),
    potential_cost_eth=2.0,
    potential_revenue_btc=0.1,
    status="NEW"
)

# Example usage:
# from database import SupabaseService
# db = SupabaseService()
# 
# # Create a council
# created_council = db.create_council(sample_council)
# 
# # Create a proposal
# created_proposal = db.create_proposal(sample_proposal)
# 
# # Create a transaction
# created_transaction = db.create_treasury_transaction(sample_transaction)
# 
# # Create an opportunity
# created_opportunity = db.create_council_opportunity(sample_opportunity)