"""
Test script for the Supabase integration
"""

import sys
import os

# Add the parent directory to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime
from maya_supabase.models import Council, Proposal, TreasuryTransaction, CouncilOpportunity
from maya_supabase.database import SupabaseService
from maya_supabase.api import router

def test_models():
    """Test that we can create model instances"""
    print("Testing model creation...")
    
    # Test Council model
    council = Council(
        id="council_digital_identity",
        council_name="Council of Digital Identity",
        domain_description="Responsible for managing digital identities",
        revenue_model_description="Earns revenue through licensing fees",
        ethical_boundary="Must ensure user privacy",
        status="ACTIVE",
        created_at=datetime.now()
    )
    print(f"Council model created: {council.council_name}")
    
    # Test Proposal model
    proposal = Proposal(
        id=None,  # This will be auto-generated by Supabase
        council_id="council_digital_identity",
        purpose="Launch 'Sign-In with Bitcoin' service",
        cost_eth=10.5,
        expected_monthly_revenue_btc=0.25,
        status="PENDING_REVIEW",
        submitted_at=datetime.now(),
        last_status_update_at=datetime.now(),
        roi_score=8.5
    )
    print(f"Proposal model created: {proposal.purpose}")
    
    # Test TreasuryTransaction model
    transaction = TreasuryTransaction(
        id=None,  # This will be auto-generated by Supabase
        timestamp=datetime.now(),
        transaction_type="COUNCIL_REVENUE_IN",
        asset="ETH",
        amount=5.25,
        description="Revenue from identity verification services",
        status="COMPLETED"
    )
    print(f"Transaction model created: {transaction.transaction_type}")
    
    # Test CouncilOpportunity model
    opportunity = CouncilOpportunity(
        id=None,  # This will be auto-generated by Supabase
        council_id="council_digital_identity",
        opportunity_description="Partnership opportunity with major DeFi protocol",
        reported_at=datetime.now(),
        status="NEW"
    )
    print(f"Opportunity model created: {opportunity.opportunity_description}")
    
    print("All models created successfully!")

def test_database_service():
    """Test that we can create the database service"""
    print("Testing database service creation...")
    
    db_service = SupabaseService()
    print("Database service created successfully!")
    print(f"Supabase client available: {db_service.client is not None}")

def test_api_router():
    """Test that we can create the API router"""
    print("Testing API router creation...")
    
    print(f"API router created with {len(router.routes)} routes")
    for route in router.routes:
        print(f"  - {route.methods} {route.path}")

if __name__ == "__main__":
    print("Running Supabase integration tests...\n")
    
    test_models()
    print()
    
    test_database_service()
    print()
    
    test_api_router()
    print()
    
    print("All tests completed successfully!")